usnistgov/oar-pdr

- .gitignore
- README.md
- proto/README.md
- proto/fedora_sample_dp/README.md
- proto/fedora_sample_dp/ingestDP.sh
- proto/fedora_sample_dp/ingestSample.sh
I've created a top-level directory, `proto`, intended for prototyping software that are not intended to be part of the operational component of PDR.
> scripts for ingesting sample data publication into Fedora

- proto/model/examples/README.md
- proto/model/examples/ceramicsportal.json
- proto/model/examples/hitsc.json
- proto/model/examples/janaf.json
- proto/model/examples/schemaLocation.json
- proto/model/nerdm-context.jsonld
- proto/model/nerdm-pub-schema.json
- proto/model/nerdm-schema-context.jsonld
- proto/model/nerdm-schema.json
- proto/model/pod-psch-onto.json
- proto/model/pod-schema.json
- proto/model/profile-schema-onto.json
This includes an example resource metadata record along with all the necessary schema and context files for validating it.
> data model schemas and first example

- metadata/README.md
- metadata/docker/mdtests/Dockerfile
- metadata/docker/mdtests/entrypoint.sh
- metadata/docker/run.sh
- metadata/python/setup.py
- metadata/scripts/install.sh
- metadata/scripts/pdl2resources.py
This is needed integration into oar-docker where I'm adding a container to load the mongodb database with NERDm records converted from a PDL catalog.
> Provide support for installation of metadata tools

- angular/src/app/landing/description/description.component.ts
- angular/src/app/landing/landing.component.css
- angular/src/app/landing/landing.component.html
- angular/src/app/landing/landing.component.ts
- angular/src/app/shared/config-service/config.service.ts
Issue reported in [ODD-614](http://mml.nist.gov:8080/browse/ODD-614)
This pull request mainly addresses the issue of files units and size display. 
1. Fixed as per requirement specified as 
when the size is 1000 bytes or greater that the value be converted to floating point with a metric byte unit such that:
* the number contain at least 3 significant digits
* there is 1-3 digits to the left of the decimal point
* there is a minimum of 1 digit to the right of the decimal point
* there is not more than 2 digits to the right of the decimal point
2. It also fixes some issue with URL rewriting when arkid specified in the url.
> Fixed the unit and filesize display.

- angular/src/app/shared/headbar/headbar.component.html
@RayPlante 
Updated the release version to 1.1.0 in header.
> Updated version number 1.1.0-beta to 1.1.0

- angular/src/app/datacart/data.ts
- angular/src/app/datacart/datacart.component.html
- angular/src/app/datacart/datacart.component.ts
- angular/src/app/landing/description/description.component.ts
- angular/src/app/landing/landing.component.ts
- angular/src/app/shared/download-service/download-service.service.ts
- angular/src/app/shared/footbar/footbar.component.css
Jira ticket: 
http://mml.nist.gov:8080/browse/ODD-750
http://mml.nist.gov:8080/browse/ODD-747
1. Fixed the status display of datacart direct download while server side returns error
2. Changed "Please try again" to "Please email us" with the email link in bundle download
3. Fixed ext link in PDR footer (ODD-747)
4. Some code clean up
makedist worked fine. Local deployment got error in oar-rmm. I believe it's tag problem. Will get the right one tomorrow and re-run.
> ODD-750-747: Improve error handling; fixed footer ext link icon

- angular/src/app/landing/landing.component.html
- angular/src/app/landing/landing.component.ts
Jira ticket: ["Superfluous "Visit Home Page" button has returned!"](http://mml.nist.gov:8080/browse/ODD-767)
Test case: 76F046F18CCA46FBE05324570681CB301977
> Hide Visit Home Page button if landing page is the home page

- angular/e2e/about/about.component.e2e-spec.ts
- angular/src/app/datacart/datacart.component.html
- angular/src/app/datacart/datacart.component.ts
- angular/src/app/frame/footbar.component.html
- angular/src/app/frame/footbar.component.spec.ts
- angular/src/app/frame/footbar.component.ts
- angular/src/app/landing/description/description.component.html
- angular/src/app/landing/description/description.component.ts
- angular/src/app/landing/landing.component.css
- angular/src/app/landing/landing.component.html
- angular/src/app/landing/landing.component.ts
- angular/src/app/landing/metadata/metadata.component.ts
- angular/src/app/landingAbout/landingAbout.component.html
- angular/src/app/shared/ga-service/google-analytics.service.ts
- angular/src/app/shared/search-service/search-service.service.ts
- angular/src/styles.scss
http://mml.nist.gov:8080/browse/ODD-785
This version added Google Analytics tracking code to all outbound, email and download links. 
A special category "datasource" was used for the outbound link to "home page" so we can query how many "Visit Home Page" hits in the report.
> Added GA event tracking

- angular/src/app/datacart/datacart.component.ts
This PR deprecates #103 from @chuanlin2018  after I botched an attempt at a rebase.  It addresses JIRA issue, [ODD-812 ("Datacart pop up only pre-select first level")](http://mml.nist.gov:8080/browse/ODD-812).  From the original PR:
> Fixed the problem that only the first level tree table in datacart was checked after user clicks on the download all button.
> 
> Almost all code was changed because I changed indent from 2 spaces to 4.
> 
> The actual changes are the following functions:
> this.buildSelectDataArray(this.dataFiles);
> this.checkNode(this.dataFiles, this.dataArray);
> ODD-812: Fixed tree table pre-select problem

- angular/src/app/frame/headbar.component.html
- angular/src/app/frame/headbar.component.ts
This PR addressing [ODD-848 ("odi contact and email information")](http://mml.nist.gov:8080/browse/ODD-848) is a "re-do" of #115 (see [this comment](https://github.com/usnistgov/oar-pdr/pull/115#issuecomment-580425978) describing why).  
From the original PR:
> I made two changes to the header menu bar in this branch:
> 
> 1. Changed "Home" icon to text "About".
> 2. Added "Contact" item that pointed to the help page in SDP.
> ODD-848: Fix About and Contact links

- angular/src/app/datacart/datacart.component.html
- angular/src/app/datacart/datacart.component.ts
http://mml.nist.gov:8080/browse/ODD-792
Fixed datacart page 508 compliance issues that I missed.
> 508 Compliance fix to datacart page

- angular/src/app/frame/footbar.component.html
- angular/src/app/frame/footbar.component.spec.ts
http://mml.nist.gov:8080/browse/ODD-853
Updated following links in the footer based on Peter's suggestion. Tested in local npm (not docker) since this is a fairly simple change:
Instagram
Looks like Travis failed while loading config data. Since this has nothing to do with this change, may be re-run Travis will fix itself?
> Updated social media link

- java/customization-api/src/main/java/gov/nist/oar/customizationapi/config/CustomFilter.java
- java/customization-api/src/main/java/gov/nist/oar/customizationapi/config/JWTConfig/JWTAuthenticationFilterLocal.java
- java/customization-api/src/main/java/gov/nist/oar/customizationapi/config/WebSecurityConfig.java
- java/customization-api/src/main/java/gov/nist/oar/customizationapi/service/JWTTokenGenerator.java
- java/customization-api/src/main/java/gov/nist/oar/customizationapi/web/LocalAuthController.java
- java/customization-api/src/main/java/gov/nist/oar/customizationapi/web/LocalSamlController.java
This pull request updates for local testing without connecting to external identity provider. 
This helps debugging functionality and provides mock authentication and authorization capabilities for test user.
> Local authentication and authorization testing

- angular/src/app/landing/citation/citation.component.ts
- angular/src/app/landing/landingpage.component.html
- angular/src/app/landing/landingpage.component.ts
http://mml.nist.gov:8080/browse/ODD-860
This branch made the citation popup responsive and the size adjust based on the screen size.
> Made the size of citation popup fit mobile screen

- angular/src/app/landing/author/author-popup/author-popup.component.html
http://mml.nist.gov:8080/browse/ODD-915
Added a set of control button (Add author, Save, Cancel) to the bottom of the author popup dialog.
Tested in docker. Teslall passed.
Queued in Travis for over an hour now...
> Added a set of control buttons at the bottom of the screen

- angular/src/app/landing/author/author-popup/author-popup.component.css
- angular/src/app/landing/author/author-popup/author-popup.component.html
- angular/src/app/landing/contact/contact-popup/contact-popup.component.css
- angular/src/app/landing/contact/contact-popup/contact-popup.component.html
- angular/src/app/landing/description/description-popup/description-popup.component.css
- angular/src/app/landing/description/description-popup/description-popup.component.html
- angular/src/app/landing/editcontrol/editcontrol.component.css
- angular/src/app/landing/editcontrol/editcontrol.component.html
- angular/src/app/landing/topic/topic-popup/search-topics.component.css
- angular/src/app/landing/topic/topic-popup/search-topics.component.html
- angular/src/styles.scss
http://mml.nist.gov:8080/browse/ODD-936
I removed button height (was set to 2em) from all "Add", "Save" and "Cancel" buttons in the edit popup dialog. Tested in Chrome and Firefox using local docker.
> Remove button height to use default

- angular/src/app/config/config.spec.ts
- angular/src/app/config/config.ts
- angular/src/app/landing/aboutdataset/aboutdataset.component.html
- angular/src/app/landing/aboutdataset/aboutdataset.component.ts
- angular/src/styles.scss
http://mml.nist.gov:8080/browse/ODD-1014
Added NERDm document link to 'About this dataset' section. It links to https://data.nist.gov/dm/nerdm/.
> Added nerdm document link

- angular/src/app/landing/sections/resourcedescription.component.html
Hot fix: enabled Research Topics section in LP.
> Enabled research topics

- angular/src/app/landing/filters/filters.component.ts
- angular/src/app/landing/keyword/keyword.component.html
- angular/src/app/landing/topic/topic.component.html
- angular/src/app/landing/topic/topic.component.spec.ts
- angular/src/app/landing/topic/topic.component.ts
http://mml.nist.gov:8080/browse/ODD-1060
This check in has following changes:
1. Separated "Research Topics" into "General Research Topics" and "Forensics Research Topics".
2.For Science Theme collection, the Forensics Research topics in the filters section now use the first two level.
3. In Subject Keywords, added a space after each comma.
4. Use italic font for all research topics and keywords.
To test, the top level "Forensics" in topics field need be removed from nerdm record first.
> Separated Forensics research topics from general ones

- angular/src/app/landing/landingpage.component.html
- angular/src/app/landing/landingpage.component.ts
- angular/src/app/landing/resultlist/resultlist.component.html
> Align 'Sort by' dropdown box with page and search boxes

- angular/src/app/metrics/horizontal-barchart/horizontal-barchart.component.ts
- angular/src/app/metrics/metrics.component.ts
- angular/src/app/shared/metrics-service/metrics.service.ts
http://mml.nist.gov:8080/browse/ODD-1054
Two changes in this checkin:
1. Remove sha files in metrics page
2. Remove some console message
To test it locally, set the following in environement.ts
useMetadataService: true,
useCustomizationService: true
editEnabled: false
> Remove sha files in metrics page; Remove some console message

- angular/src/app/landing/author/author-popup/author-popup.component.html
- angular/src/app/landing/author/author.component.html
- angular/src/app/landing/facilitators/facilitators.component.html
- angular/src/app/landing/resultlist/resultlist.component.html
http://mml.nist.gov:8080/browse/ODD-1061
This check in added alt text to all img tags in pdr.
> Added alt text to img tags

- angular/src/app/app.component.ts
- angular/src/app/config/config.ts
- angular/src/app/shared/ga-service/google-analytics.service.ts
- angular/src/environments/environment.ts
http://mml.nist.gov:8080/browse/ODD-1091
This branch added Google Analytics code to PDR.
To test it locally (if you already created an account for SDP testing, it also works for PDR. You can start from step 6),
1. Login your gmail account
2. Go to https://analytics.google.com/, click on the "admin" icon at bottom left of the screen
3. Create a new account.
4. Add a new Data Streams and set the stream url to http://127.0.0.1 and provide a stream name.
5. Note MEASUREMENT ID generated by Google Analytics.
6. Replace src/assets/environment.ts and replace the value of "GA4CODE" with the MEASUREMENT ID got from step 5.
7. Compile and run PDR by using "npm i" and "npm start" command.
8. Open http://localhost:4200/od/id/test1
9. Open https://analytics.google.com/, select the GA account you just …
> Added Google Analytics 4

- angular/src/app/landing/landingpage.component.ts
- angular/src/app/metrics/metrics.component.html
- angular/src/app/metrics/metrics.component.ts
- angular/src/app/shared/metrics-service/metrics.service.ts
Issue: https://sgitlab.nist.gov/oar-odd/landing-page-service/-/issues/3
Landing page crashed because there was no pdrid in metrics data.
Fix: Added pdrid check in getMetrics() in both landingpage and metrics component.
> Handled missing pdrid in metrics

- python/nistoar/pdr/preserv/bagger/midas3.py
- python/nistoar/pdr/publish/midas3/service.py
This PR attempts to fix some intermittent bugs that result in preservation failures that do not result in a failure notification.  Namely,
* A preservation request would fail because the reference to the review directory would set to None
* A preservation request would to launch asynchronously in a separate thread without raising a catchable exception.
As these bugs were difficult to debug in a dev environment, they were deployed as a hot fix to datapub.nist.gov.  Since then, preservation requests have been completing successfully, and neither of the above failures appear to have occurred.  (At the very least, the fix did not appear to break anything.)
> Fix preservation workflow bugs

- angular/src/app/_helpers/fakeBackendInterceptor.ts
- angular/src/app/app.module.ts
Two changes in this check in:
1. disable fake backend in app.module.ts
2. Added alert to fake backend interceptor.
Unable to test the bundle download function with fake backend disabled...
> Disabled fake backend

- .github/workflows/angular-source.yml
- .github/workflows/integration.yml
- .github/workflows/java-source.yml
- .github/workflows/main.yml
- .github/workflows/python-source.yml
- .github/workflows/testall.yml
- angular/src/app/app-routing.module.ts
- angular/src/app/app.module.ts
- angular/src/app/bulk-download/bulk-download.component.css
- angular/src/app/bulk-download/bulk-download.component.html
- angular/src/app/bulk-download/bulk-download.component.spec.ts
- angular/src/app/bulk-download/bulk-download.component.ts
- angular/src/app/bulk-download/bulk-download.module.ts
- angular/src/app/datacart/cartcontrol/cartcontrol.component.html
- angular/src/app/landing/aboutdataset/aboutdataset.component.html
- angular/src/app/landing/data-files/bulk-confirm/bulk-confirm.component.css
- angular/src/app/landing/data-files/bulk-confirm/bulk-confirm.component.html
- angular/src/app/landing/data-files/bulk-confirm/bulk-confirm.component.spec.ts
- angular/src/app/landing/data-files/bulk-confirm/bulk-confirm.component.ts
- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/app/landing/data-files/data-files.module.ts
- angular/src/app/landing/tools/menu.component.html
- angular/src/app/landing/tools/menu.component.ts
- angular/src/app/landingAbout/landingAbout.component.css
- angular/src/app/metrics/metrics.component.html
- angular/src/environments/environment.ts
- angular/src/styles.scss
For review only. Don't merge just yet.
I added the following field to environemt.ts:
downloadableFileLimit: 300,
> Added bulk download feature
