- metadata/docker/jq/Dockerfile
As discussed in #7, there was probably one more checksum than there needed to be, and the extra one was not working consistently on windows (despite the changes merged as part of #8).  This fix pulls the checksum of the checksum file out.
> Fix checksum problem on windows (2nd attempt at #7)

- metadata/docker/ejsonschema/Dockerfile
The `Dockerfile` in `metadata/docker/ejsonschema` sets up python-related dependencies.  Somewhere in my rush to merge in the checksum fixes (#7), I seem to have lost a previous update that installs the pynoid python library, needed by the `pdl2resources.py` script.
> Replace pynoid installation into ejsonschema Dockerfile

- metadata/jq/pod2nerdm.jq
- metadata/model/nerdm-schema.json
Som found a few issues that are fixed in this PR:
* converter was output-ing a "hasEmail" property instead of "email" as specified by schema; changed to schema to change property name to "hasEmail" for closer correspondance to pod.  (This introduces a little naming inconsistency within ContactInfo, though.)
* converter was not passing "theme"; updated `pod2nerdm.jq`
> fix jq conversion problems:  hasEmail, theme

- python/nistoar/pdr/preserv/bagit/bag.py
- python/nistoar/pdr/preserv/bagit/builder.py
- python/tests/nistoar/pdr/preserv/bagger/test_midas.py
- python/tests/nistoar/pdr/preserv/bagit/test_bag.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
From [ODD-446](http://mml.nist.gov:8080/browse/ODD-446):
> The mdserver examines datasets under construction via MIDAS and creates NERDm records from them which can be rendered by the internal landing page service. The service is not correctly generating a `dataHierarchy` property in the NERDm record that fully reflects the contents in the components listing. Since the landing page service uses the former to generate the file listing in HTML, the landing page fails to list some of the files.
This PDR fixes this bug by using the [related fix to oar-metadata](https://github.com/usnistgov/oar-metadata/pull/10) and ensuring that a complete `dataHierarchy` is generated based on the files present in the input directories (and not just what was mentioned in the POD record).
> mdserver: ensure all files appear in dataHierarchy property

- python/nistoar/pdr/preserv/bagger/midas.py
- python/tests/nistoar/pdr/preserv/bagger/test_midas.py
- python/tests/nistoar/pdr/preserv/data/midassip/review/1491/_pod.json
- python/tests/nistoar/pdr/preserv/data/midassip/upload/1491/_pod.json
- python/tests/nistoar/pdr/publish/mdserv/test_serv.py
- python/tests/nistoar/pdr/publish/mdserv/test_webservice.py
- python/tests/nistoar/pdr/publish/mdserv/test_wsgi.py
This PR addresses [ODD-604 ("PDR-publish misses external distributions")](http://mml.nist.gov:8080/browse/ODD-604) which considers a problem handling a MIDAS SIP that includes distributions available from external URLs--i.e. not through the distribution service (including via s3.amazonaws.com and cloud front).  Such distributions would not get translated into the NERDm record via the metadata service.  Thus, these distributions would not be listed on the landing page.  
This scenario came up with a MIDAS SIP that was initiated prior to the MIDAS-PDR integration but is ready to publish afterward.  However, this problem would likely also arise when updating datasets that were published prior to the MIDAS-PDR integration.
Previously, NERDm record components were based exclusively on the …
> ODD-604: md service: don't lose external distributions

- python/nistoar/pdr/preserv/bagit/builder.py
This PR is a follow-up to PR #28 which addresses [ODD-604 ("PDR-publish misses external distributions")](http://mml.nist.gov:8080/browse/ODD-604); that issue considers a problem handling a MIDAS SIP that includes distributions available from external URLs--i.e. not through the distribution service (including via s3.amazonaws.com and cloud front).  It's typical that a dataset with at least one external distribution will have all its distributions external.  Thus, a preservation bag for the dataset will contain no payload data under its `data` directory.  A feature of the service to eliminate empty subdirectories under `data` (e.g. when data files have been remove) was, in such a case, also eliminating the `data` directory, making it no longer a compliant bag.  
This PR fixes the folder …
> ODD-604:  preservation service: don't delete empty data directory

- python/nistoar/pdr/preserv/bagit/builder.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
- python/tests/nistoar/pdr/preserv/data/metadatabag/metadata/nerdm.json
- python/tests/nistoar/pdr/preserv/data/metadatabag/metadata/pod.json
- python/tests/nistoar/pdr/preserv/data/midassip/review/1491/_pod.json
- python/tests/nistoar/pdr/preserv/data/midassip/upload/1491/_pod.json
- python/tests/nistoar/pdr/preserv/data/samplembag/about.txt
- python/tests/nistoar/pdr/preserv/data/samplembag/metadata/nerdm.json
- python/tests/nistoar/pdr/preserv/data/samplembag/metadata/pod.json
- python/tests/nistoar/pdr/preserv/data/simplesip/_nerdm.json
- python/tests/nistoar/pdr/preserv/data/simplesip/_pod.json
Hello :-)
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates static DOI links and the code that generates new ones.
Cheers!
> Link DOIs to preferred resolver

- python/nistoar/pdr/preserv/bagit/builder.py
- python/tests/nistoar/pdr/preserv/bagger/test_midas.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
- python/tests/nistoar/pdr/preserv/data/midassip/review/1491/_pod.json
This addresses [ODD-612 ("PDR-publish: files with URL-encodable parameters get listed twice")](http://mml.nist.gov:8080/browse/ODD-612) which describes how special characters in filenames were confusing the metadata service and causing them to be added twice, one with the characters URL-encoded and one unencoded.  The key to fixing this is ensuring that when converting between `downloadURL` and `filepath` properties, it is necessary to url-encode and decode.  
This PR has a companion [PR 25 to oar-metadata](https://github.com/usnistgov/oar-metadata/pull/25).  In this PR, the `bagit/builder` module was updated to encode the `filepath` when converting it to a `downloadURL` or a component ID (`@id`).  (The [oar-metadata PR 25](https://github.com/usnistgov/oar-metadata/pull/25) handles …
> ODD-612: urlencode the filepath when converting to downloadURL

- python/nistoar/pdr/preserv/bagit/builder.py
- python/nistoar/pdr/utils.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
- python/tests/nistoar/pdr/test_utils.py
This PR addresses two bugs causing preservation failures, one related to descriptions with empty paragraphs and the other resulting when preservation is retried after an initial failure.  
As described in the [oar-metadata PR 26](https://github.com/usnistgov/oar-metadata/pull/26), a preservation bagging failure can occur one of the values in the NERDm record's (Resource-level) `description` property array is an empty string (or one containing only spaces): when the description is used to fill in the `External-Description` property in the `bag-info.txt` file, one of its entries would have no value, causing a bag validation error.  The origin of this error was MIDAS users being over-eager with the return key when entering a resource description.  The [oar-metadata …
> Fix preservation failures due to funny descriptions and retries

- python/nistoar/pdr/preserv/bagger/midas.py
- python/nistoar/pdr/preserv/bagit/bag.py
- python/nistoar/pdr/preserv/bagit/builder.py
- python/nistoar/pdr/publish/mdserv/serv.py
- python/tests/nistoar/pdr/preserv/bagit/test_bag.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
- python/tests/nistoar/pdr/preserv/data/metadatabag/metadata/annot.json
- python/tests/nistoar/pdr/preserv/data/metadatabag/metadata/trial1.json/annot.json
- python/tests/nistoar/pdr/publish/mdserv/test_serv.py
This PR addresses ODD-636 ("Complete support for NERDm annotations in PDR Publishing system") which will allow us to make manual modifications to NERDm records that are simultaneously being edited via MIDAS. (Annotations are edits to the metadata that would normally occur through the PDR publishing interface; these are merged with metadata that originate from MIDAS via the POD record.) This PR requires the [oar-metadata PR 27](https://github.com/usnistgov/oar-metadata/pull/27) which provides needed updates to the merging conventions.
To "turn on" annotation support (which was largely already implemented), I had to:
- Have the metadata server request NERDm records with annotations merged in
- Implement the place-holder `ensure_merged_annotations()` function to merge annotations into the …
> ODD-636: Support annotations in the PDR publishing system

- docker/pdrtest/entrypoint.sh
- python/nistoar/pdr/preserv/service/wsgi.py
A large data submission triggered asynchronous completion of the preservation request, triggering a failure in submitting the HTTP response message.  This was due to a bug in an incorrect retrieval on the message from the preservation status object.  This has been corrected.  
I note that despite this failure, the preservation request should have still continued to successful completion, but it did not.  With further investigation, it was found that the `uwsgi` launching program was missing a required `--enable-threads` argument.  Apart from the context of PDR unit testing, this is handle by [`oar-docker`](https://github.com/usnistgov/oar-docker/); thus there is [a companion PR for that repository (PR 100)](https://github.com/usnistgov/oar-docker/pull/100) as well.
> preservation service bug fix: correct failing async response message

- python/nistoar/pdr/preserv/bagit/builder.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
We saw a failure in the preservation service when the description contained a unicode character.  This was traced to `nistoar.pdr.preserv.bagit.builder` when writing the `about.txt` file to the preservation bag: the unicode character was not getting properly encoded for the ASCII-formatted file, resulting in an `UnicodeEncodingError`.  This PR fixes this bug.  All metadata from the source POD and NERDm files are properly encoded for "utc-8" as they are written to the `about.txt` file.  The associated unit test was updated to inject a unicode character to test proper encoding.
> Preservation Service bug fix: allow for unicode when writing about.txt

- python/nistoar/pdr/preserv/bagit/validate/multibag.py
The Multibag BagIt Profile spec allows an info tag element called `Multibag-Head-Deprecates` that can be used to indicate the existence of previous versions of the aggregation.  The Multibag validator (`nistoar.pdr.preserv.bagit.validate`) checks to make sure a head bag doesn't claim to deprecate itself ("self-deprecation").  There was a bug in how this check was down, and this PR fixes it.
> multibag validation: fix check of self-deprecation

- docker/pdrtest/entrypoint.sh
- python/nistoar/pdr/preserv/service/wsgi.py
- python/tests/nistoar/pdr/preserv/service/test_wsgi.py
This PR addresses a special issue with the MIDAS interface (and addresses a request from Chris).  MIDAS, as a Java application on the backend, uses the default Java 8 URL classes to connect to a service; these default classes do _not_, as is, support the lesser-used (though standard) HTTP methods like PATCH.  The simplest work-around is to use the [X-HTTP-Method-Override header variable](https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch); however, this variable must be explicitly supported on the server.  This PR adds that support which allows a POST support to be converted to a PATCH.
> Preservation Service: add support for X-HTTP-Method-Override for MIDAS

- oar-build/_run.sh
- oar-build/_setversion.sh
- scripts/makedist
- scripts/makedist.angular
- scripts/makedist.python
The `makedist` and `setversion.sh` shell scripts both contained commands that are not supported on MacOS--`realpath` and `sed -r`--causing `makedist` to fail on that platform.  These have been replaced with Mac-compatible alternatives.  (See also [oar-sdp PR# 199](https://github.com/usnistgov/oar-sdp/pull/199)).  
To test, just run `scripts/makedist` on a Mac to make sure it builds successfully.  It is not necessary to run the PDR application.
> Fix MacOS-specific bug preventing makedist from working

- angular/package.json
[ODD-715](http://mml.nist.gov:8080/browse/ODD-715) describes an error that arose recently when building oar-pdr from scratch due to a recent update to the rxjs package.  (See the [JIRA ticket](http://mml.nist.gov:8080/browse/ODD-715) for error message details.) The [rxjs repo](https://github.com/ReactiveX/rxjs) indicates that it requires at least v2.8 for typescript; our `package.json` file was set to use `~2.7.4`.  This PR updates that file to use `~2.8.4`.
> ODD-715: update typescript version

- angular/package.json
- python/nistoar/pdr/preserv/service/siphandler.py
- scripts/testall.python
[ODD-712](http://mml.nist.gov:8080/browse/ODD-712) briefly describes how when a fatal failure occurs during preservation, the bag's internal log file does not get closed.  This causes problems removing the failed bag when the bag is on an NFS-mounted system, as it is on the test and production platforms. 
This small fix corrects this bug.  This PR also includes a fix to the `scripts/testall.python` script that ensures that it can run standalone.
> ODD-712:  close bag's log on failure

- angular/src/app/datacart/datacart.component.html
- angular/src/app/datacart/datacart.component.ts
- angular/src/app/landing/description/description.component.html
- angular/src/app/landing/description/description.component.ts
1. Fixed file detail popup dialog word wrap problem
2. Changed direct download function from http request to direct download because server side does not allow CORS. The code was commented out but not removed so we can easily revert once server side is fixed.
Makedist and docker local deployment were successful.
> ODD753-757: Popup word wrap and direct download

- docker/pdrtest/Dockerfile
Something appears to have change in the python module dependency chain (probably related to [oar-metadata PR#31](https://github.com/usnistgov/oar-metadata/pull/31)), and now the python module, funcsigs, is an explicit dependency for the [NIST mulibag module](https://github.com/usnistgov/multibag-py).  In this PR, this module is now explicitly pip-installed in the `docker/pdrtest/Dockerfile`.  Without this change, the python tests fail.
> Fix docker build: install python module, funcsigs

- angular/e2e/about/about.component.e2e-spec.ts
- angular/package-lock.json
- angular/package.json
- angular/src/app/app-routing.module.ts
- angular/src/app/frame/headbar.component.html
- angular/src/app/frame/headbar.component.spec.ts
- angular/src/app/shared/ga-service/google-analytics.service.mock.ts
- angular/src/app/shared/ga-service/google-analytics.service.ts
I am using the same JIRA tracker 773.
As mentioned in the email, the tracking code on outbound event was not working correctly. So I am using the previous approach for now - using router event to track page view only.
There are only landing page, datacard page and about page in pdr. Make sure when click on those pages you see "collect" events in the Network tab in developer Tools.
> Changed GA for page view only. 

- angular/src/app/app-routing.module.ts
- angular/src/app/shared/ga-service/google-analytics.service.ts
whenever user visits PDR landing page or datacart page, GA generates two page views instead of one. This was because we always start datacart in the separated page which was considered a new page by the browser. So the page view was sent to GA server by both original script in index.html and the router event. Since PDR only has "landing", "about" and "datacart" pages and those are all "new page", no extra GA code is necessary in the router event.
So in this fix, I just simply remove the function in GA service. But I left the structure there because we need to track other events such as outbound click, download, etc.
> Fixed dup page views

- python/nistoar/pdr/preserv/bagger/prepupd.py
- python/nistoar/pdr/preserv/bagit/builder.py
In oar-pdr [v1.2.2](https://github.com/usnistgov/oar-pdr/releases/tag/1.2.2) (deployed as part of  v1.20 of oar-docker), the landing page service was failing to serve up pre-publication previews of the landing page; this was because the metadata server was still attempting to validate the ARK id for its check character, even though the service was configured not to for the new ARK ID format.  This error was traced to a use of the `BagBuilder` class within `nistoar.pdr.preserv.bagger.prepupd` where a `BagBuilder` instance was being instantiated without any configuration.  The default value of the `validate_id` config parameter is currently set to `True`; so the check was being erroneously applied.  This PR fixes this by providing an explicit configuration with this parameter set to …
> Fix ID validation failure in pre-pub metadata server

- python/nistoar/pdr/preserv/service/service.py
- python/nistoar/pdr/preserv/service/wsgi.py
In oar-pdr [v1.2.2](https://github.com/usnistgov/oar-pdr/releases/tag/1.2.2), the preservation service would fail to preserve an update when the SIP uses an ARK-based identifier.  This was because the service was trying to cache a copy of the published NERDm record in a cache directory with the name `ark:/xxxxx/mds2-yyyy.json`  This PR corrects this problem, allowing such updates to be supported.
> Fix preservation failure when updating a submission having an ARK SIP identifier

- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/environments/environment.ts
This PR address [ODD-844 ("LPS: Access URLs no longer showing up on Landing Page")](http://mml.nist.gov:8080/browse/ODD-844) that observed that the accessURL rendering was based on the deprecated `inventory` NERDm property, causing them not to appear in new records.  This fix replaces the management of accessURL data in the `data-files` component.
> ODD844: Display access URLs

- angular/src/app/landing/contact/contact.component.html
- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/data-files/data-files.component.ts
I removed GA tracking function from contact, home page and direct download links so they won't be double tracked. I was unable to recreate the problem locally. So can only test the result in testdata for now.
The code is based on integration13.
> Remove some manual GA tracking code

- angular/src/app/landing/citation/citation.component.spec.ts
- angular/src/app/landing/citation/citation.component.ts
- angular/src/app/landing/citation/citation.module.ts
- angular/src/app/landing/landing.component.html
- angular/src/app/landing/landing.component.spec.ts
- angular/src/app/landing/landing.component.ts
- angular/src/app/landing/landing.module.ts
- angular/src/app/landing/landingpage.component.css
- angular/src/app/landing/landingpage.component.html
- angular/src/app/landing/landingpage.component.spec.ts
- angular/src/app/landing/landingpage.component.ts
- angular/src/app/landing/landingpage.module.ts
- angular/src/app/landing/tools/toolmenu.component.css
- angular/src/app/landing/tools/toolmenu.component.spec.ts
- angular/src/app/landing/tools/toolmenu.component.ts
- angular/src/app/landing/tools/tools.module.ts
- angular/src/app/nerdm/nerdm.spec.ts
- angular/src/app/nerdm/nerdm.ts
- angular/src/environments/environment.ts
This PR is part of an ongoing effort at restructuring the angular Landing Page Service (LPS) app in an effort to improve maintainability and ease further evolution of the presentation.  Its overall goal is to distribute the current `LandingComponent` into several smaller apps that are aggregated together.  This PR, in particular, breaks out the right-hand tools menu into is own component, leaving the `LandingComponent` to handle just the main body of the landing page content.  While implementation of the menu is largely unchanged, it is a helpful precursor to replacing the tool bar with an implementation that is primeng-free (as the primeng components don't work with the server-side rendering).  
The change provided by the PR is summarized in the following diagrams.  
In particular, the …
> LPS Restructuring Con't:  New Tools Component

- python/setup.py
- python/tests/nistoar/pdr/preserv/bagger/test_datachecker.py
- python/tests/nistoar/pdr/preserv/service/test_siphandler_multibag.py
This PR fixes some unit tests that sometimes fail or hang because they rely on accessing the production distribution service on data.nist.gov.  Instead, these unit tests now use a simulated distribution service running locally.  
This PR leverages the [PR#34 from oar-metadata](https://github.com/usnistgov/oar-metadata/pull/34) that modifies the conversion of POD records to NERDm which previously was too specific to data.nist.gov.  Conversion will now recognize distribution service URLs from any server, including a locally running one.
> python: fix tests that rely on data.nist.gov

- angular/src/app/shared/ga-service/google-analytics.service.ts
http://mml.nist.gov:8080/browse/ODD-826
As the title said, this change removed "yt=true" from Gogle Analytics string.
> Remove yt=true from google analytics string

- angular/src/app/landing/landing.component.html
- angular/src/app/landing/landing.component.spec.ts
- angular/src/app/landing/landing.component.ts
When the `landingPage` metadata property points to an external web site, a button should appear at the top of the landing page that links to the landing page; if it's a PDR landing page URL, the button should not appear.  The code that detects an external URL was not properly recognizing PDR URLs using the new identifier pattern and the corresponding convention for the PDR landing page URL.  This PR updates to the implementation to recognize these URLs.
I also include a minor change that renders button as a traditional link when rendering on the server.
> angular: landing page: fix detection of PDR landing pages

- angular/src/app/landing/landing.component.html
- angular/src/app/landing/landing.component.ts
- angular/src/app/landing/landingpage.component.html
- angular/src/app/landing/landingpage.component.ts
In the last PDR-LPS code restructuring iteration, the "View Metadata" item in the right-side tools menu stopped working.  This PR restores its functionality.
Note that metadata visualization is expected to change in further iterations of the code restructuring.
> Restore "View Metadata" function

- python/nistoar/pdr/utils.py
- python/tests/nistoar/pdr/test_utils.py
In the python-based publishing code, reading and writing of NERDm metadata files are supposed be protected in a multi-threaded/multi-processing application.   In particular, some of the processing triggered by mdserver/preserver web service calls that result in updating metadata files is done asynchronously--i.e. in a separate thread--so that web service calls can return quickly.  Despite the file locking that's in place, we would still on occasion see file write collisions:  the same metadata data would get written twice sequentially into a file.  This PR fixes that bug.  
The file locking that was in place was the use of python's `lockf()` function.  It turns out that this function only provides protection across multiple processes.  This is important for protecting the metadata and …
> Fix NERDm file locking bug

- python/nistoar/pdr/preserv/bagger/midas.py
- python/tests/nistoar/pdr/preserv/bagger/test_midas.py
There is a bug in the Python publishing code such that when a user removes a file and its corresponding `.sha256` file via MIDAS, MIDAS will remove both entries in the POD record; however, only the file would get removed from the NERDm metadata.  Consequently, the landing page would continue to show the sha files for files that had been removed.  This PR corrects this bug.
> publish bug fix: remove sha file entries from NERDm when files are remove

- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
This PR addresses ticket [ODD-859](http://mml.nist.gov:8080/browse/ODD-859) which reported that themes that users selected in MIDAS were not appearing as research themes on the landing page; further, many records were showing in the SDP search results as having the research themes as "unspecified".  This PR uses an underlying fix applied to `oar-metadata` ([PR#35](https://github.com/usnistgov/oar-metadata/pull/35)).
As described in [`oar-metadata` PR#35](https://github.com/usnistgov/oar-metadata/pull/35), themes are handled in a special way in the PDR publishing system because in the original, pre-PDR POD records, full taxonomy terms were not be properly specified: only the lowest (most-specific) term was being set.  For example, "Glycomics" would be specified rather than "Bioscience: …
> ODD-859: Fix propagation of research themes into NERDm records

- python/nistoar/pdr/preserv/bagit/builder.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
This PR addresses ticket [ODD-881](http://mml.nist.gov:8080/browse/ODD-881) that describes how during the publication process download URLs can get overridden when files are examined to extract extra metadata.  This was seen with new-style identifiers (e.g. `ark:/88434/mds2-7777`) in which a download URL that appears in the pod file like, say, `https://data.nist.gov/od/ds/mds2-7777/README.txt`, would get replaced in the NERDm file with `https://data.nist.gov/od/ds/ark/88434/mds2-7777/README.txt`.  While both URLs work in the PDR, the former is preferred.
> ODD-881: don't let file examination override download URL

- java/customization-api/src/main/java/gov/nist/oar/customizationapi/helpers/JSONUtils.java
- java/customization-api/src/main/resources/logback.xml
- java/customization-api/src/main/resources/static/json-customization-schema.json
The customization service (CS) was raising validation exceptions when the landing page service 
(LPS) submitted author updates.  This was due in part because the latter was sending empty values for fields that the user did not fill in.  Leaving values empty, of course, is normal.  Rather than making the LPS remove unfilled properties, I thought it would be simpler to loosen the JSON schema definition the CS using to validate the changes.  The pubserver can scrub the changes more thoroughly to match the NERDm schema definition when it receives all the updates.  
I also tweaked the validation check to log all of the specific errors found in validation to aid in debugging such issues.
> Customization: loosen validation restrictions on JSON submitted to /lp/editor

- angular/src/app/landing/contact/contact.component.html
- angular/src/app/landing/contact/contact.component.ts
Jira ticket: http://mml.nist.gov:8080/browse/ODD-717
The example in the ticket (808B2042D1696C0BE05324570681AB642018) already has "mailto:" in the field and I couldn't find a test record. I tested it in local using test1 data. I confirmed the old version won't display the email if I removed "mailto:" and in the new version the email address always displayed regardless if there was "mailto:" or not.
> Handle email without mailto:

- angular/src/app/landing/landing.component.ts
- angular/src/assets/mds2-2225.json
- angular/src/assets/sample1.json
A recent submission (mds2-2225) highlighted some problems with the display versions on the landing page:
* Sometimes, the message about a newer version available would erroneously appear; this is apparently due to an error in sorting versions.
* Links to previous versions really only resolved to the latest version.  
This is the subject of [ODD-910](http://mml.nist.gov:8080/browse/ODD-910) which is addressed in this PR.
This problem has been addressed in a somewhat temporary way:
* The message about  a newer version is suppressed when the it relies on version sorting; It will still appear if the record has a "isReplacedBy" property (which is still relevant in a few cases).
* Links to previous versions in the Version History listing have been removed, unless they point to a record with a …
> ODD-910: Fix Landing Page Version Links and Labeling

- angular/src/app/landingAbout/landingAbout.component.html
As you can see in the comments I misspelled "github" as "giyhub" :)
The fix in this branch is simple - just fixed the Github url.
> Fixed github link

- .travis.yml
- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/app/landing/landing.component.html
- angular/src/app/landing/landing.component.ts
- angular/src/environments/environment.ts
- python/nistoar/pdr/preserv/bagger/utils.py
- python/nistoar/pdr/preserv/bagit/builder.py
- python/nistoar/pdr/preserv/bagit/tools/enhance.py
- python/nistoar/pdr/publish/midas3/service.py
- python/nistoar/pdr/publish/midas3/wsgi.py
- python/tests/nistoar/pdr/preserv/bagger/test_prepupd.py
- python/tests/nistoar/pdr/preserv/bagger/test_utils.py
- python/tests/nistoar/pdr/preserv/bagit/test_builder.py
- python/tests/nistoar/pdr/preserv/bagit/tools/test_enchance.py
- python/tests/nistoar/pdr/preserv/data/samplembag/metadata/nerdm.json
- python/tests/nistoar/pdr/preserv/data/simplesip/_nerdm.json
- python/tests/nistoar/pdr/publish/midas3/test_service_preserve.py
- python/tests/nistoar/pdr/publish/midas3/test_wsgi_preserve.py
- scripts/dhsetup.sh
- scripts/tests/test-preserv.sh
This PR addresses [ODD-954 ("pubserver: require POD record as input to preservation request")](https://mml.nist.gov:8080/browse/ODD-954) which calls for a change to the preservation service API intended to prevent a common failure mode.  The fix now requires that the latest POD record to be provide as input to the preservation request to ensure that archived POD data is in sync with MIDAS, and most importantly, to ensure that the latest date held by MIDAS is actually valid.  The preservation service now processes the POD record just as if it was sent to the `/latest/` pubserver endpoint, and then proceeds with preservation; if the POD record is invalid, preservation is not carried out, and the client returned an error status.  
Test this PR via the [oar-docker …
> ODD-954: Require POD as input to preservation service

- angular/src/app/frame/headbar.component.ts
http://mml.nist.gov:8080/browse/ODD-934
This fix modified the url of contact link to be the same as the one in SDP - from help/app-contact-us to help/contactus.
To test, run it in local docker and click on "Contact" at top right menu. Make sure the target is https://data.nist.gov/sdp/#/contactus.
> Modified contact url link to be the same as in SDP

- angular/src/app/datacart/bundleplan/bundleplan.component.html
- angular/src/app/datacart/bundleplan/bundleplan.component.ts
- angular/src/app/datacart/cart.service.ts
- angular/src/app/datacart/cart.spec.ts
- angular/src/app/datacart/cart.ts
- angular/src/app/datacart/cartcontrol/cartcontrol.component.html
- angular/src/app/datacart/cartcontrol/cartcontrol.component.ts
- angular/src/app/datacart/datacart.component.html
- angular/src/app/datacart/datacart.component.ts
- angular/src/app/datacart/datacart.module.ts
- angular/src/app/datacart/datacart.routes.ts
- angular/src/app/datacart/download-confirm/download-confirm.component.ts
- angular/src/app/datacart/treetable/treetable.component.html
- angular/src/app/datacart/treetable/treetable.component.ts
- angular/src/app/directives/contenteditable-model.directive.ts
- angular/src/app/form-can-deactivate/form-can-deactivate.ts
- angular/src/app/landing/author/author.component.ts
- angular/src/app/landing/contact/contact.component.ts
- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/app/landing/downloadstatus/downloadstatus.component.ts
- angular/src/app/landing/editcontrol/editcontrol.component.ts
- angular/src/app/landing/editcontrol/editstatus.service.ts
- angular/src/app/landing/landing.module.ts
- angular/src/app/landing/landingpage.component.ts
- angular/src/app/landing/search-service.resolve.ts
- angular/src/app/shared/download-service/download-service.service.ts
- angular/src/app/shared/ga-service/google-analytics.service.ts
http://mml.nist.gov:8080/browse/ODD-955
http://mml.nist.gov:8080/browse/ODD-956
http://mml.nist.gov:8080/browse/ODD-957
This check in addresses above three tickets. 
For ODD-955 - Unable to Download-All on mds2-2253, it was caused by Google Analytics script because it takes too long to analyze the datacart page. Fixed this issue by moving GA call to after user confirm downloading. This is logically correct and solved timeing issue.
ODD-956 - server side error: fixed by adding inBrowser flag to non-server-side calls.
ODD-957 - remove dependency on EditStatusService in DataFilesComponent: the service was originally designed for other component but later on the design changed. Used a function call instead of doing a round-trip call. The un-used service was also removed.
Test it in local …
> Fix/odd955-956-957 download all failure on mds2-2253, server side error and code clean up

- python/nistoar/pdr/publish/midas3/service.py
- python/nistoar/pdr/publish/midas3/wsgi.py
- python/tests/nistoar/pdr/publish/midas3/test_wsgi_preserve.py
This is a follow-up to #168: as part of the API change to the preservation service, the service will return to MIDAS more extensive error messages if the submitted POD record is invalid.  This allows the MIDAS team and/or the curator potentially more ability to assess what is wrong with the record.  
This will be tested as hotfix on datapubtest in lieu of normal review.  This PR is provided as a record for the addendum.
> ODD954 update: return more error content to MIDAS

- angular/src/app/frame/headbar.component.html
http://mml.nist.gov:8080/browse/ODD-960
This fix Changed "Contact" to "Help" in the header bar. To test, run it in docker.
> Changed Contact Us to Help

- python/nistoar/pdr/publish/midas3/mdwsgi.py
This PR addresses ODD-953 ("Datapub direct file download") which observes that files downloaded via the proto-landing page on the publishing platform (`datapub`) are being saved with names of the form, `download.`*.  A related symptom is that files with a comma in the name fail to download with the browser reporting a "Network error".  This is due to an incorrect format for the value being set for the `Content-Disposition` HTTP Header by the metadata server.  This corrects the value by setting it to `inline; filename="`_filename_`"`.
> mdserver: fix renaming of files downloaded from publishing platform

- angular/src/app/landing/tools/toolmenu.component.ts
No Jira ticket associate to this quick fix.
This fix is to display "Metrics not available" in the green menu in landing page if no file was downloaded regardless how many users were recorded in the metrics data.
Attached files show how the menu look like before and after the change.
> Display no matrics available if nothing was downloaded

- docker/pdrtest/Dockerfile
- etc/mako/readme/data_overview.txt
- etc/mako/readme/data_use.txt
- etc/mako/readme/front_matter.txt
- etc/mako/readme/general_info.txt
- etc/mako/readme/methods.txt
- etc/mako/readme/references.txt
- etc/mako/readme/version_history.txt
- python/nistoar/pdr/publish/cmd/__init__.py
- python/nistoar/pdr/publish/cmd/readme.py
- python/nistoar/pdr/publish/midas3/mdwsgi.py
- python/nistoar/pdr/publish/readme.py
- python/tests/nistoar/pdr/preserv/bagit/tools/test_enchance.py
- python/tests/nistoar/pdr/publish/midas3/test_mdwsgi.py
- python/tests/nistoar/pdr/publish/test_readme.py
This PR adds a new service to the publishing metadata service that automatically creates a README file for a submission constructed out of its NERDm metadata.  Users can download the file, edit it, and then submit it to MIDAS as a normal distribution file.   
The auto-generation is accessed via the URL, `/midas/`_id_`/README.txt?auto=1`.  This will return the generated README text file; by default, this text will include prompts to the use to aid in editing file.  An additional parameter to the URL, `flags`, modifies the output.  If the value includes a `P`, editing prompts will be excluded.  If `B` (mnuemonic: "brief") is included, the README will not list the files in the collection (helpful when the collection is large).  
This was tested by a user testing group via midastraining and …
> Provide a README auto-generation capability for use by MIDAS

- angular/src/app/metrics/metrics.component.ts
This check in fixed two issues:
1. Not all metrics data show up in the chart - somehow Object.assign() didn't append objects but replace object instead. It ended up we only have the last folder's data in the chart.
2. The total downloads of each folder didn't show up in the tree table - handleSum() was moved to a wrong location in one of previous check in.
> Fixed missing metrics data;Display folder level downloads in tree table

- angular/src/app/landing/landingpage.component.ts
This check in added a guard to get metrics function to prevent loading metrics data when edit is enabled.
Since this is a fairly simple change I didn't test it in local oar docker...
> Do not check metrics when edit enabled

- .github/workflows/angular-source.yml
- .github/workflows/integration.yml
- .github/workflows/java-source.yml
- .github/workflows/main.yml
- .github/workflows/python-source.yml
- .github/workflows/testall.yml
- README.md
Travis-CI has been used as our continuous integration service that automatically runs unit tests with every push and pull request to the repository.  With Travis-CI's reduction of free limits, we are migrating our CI scripts to GitHub Actions.  This PR introduces those scripts (held in `.github/workflows`).  GitHub Actions provides greater flexibility for configuring triggered workflows, so several scripts are introduced following the patter established in [oar-rmm](https://github.com/usnistgov/oar-rmm) (see [PR#36](https://github.com/usnistgov/oar-rmm/pull/36)).  
To test, ensure that the GitHub action check-marks appear in this PR page. Click on the mark to access the log for the action.
> Add support for github actions as replacement for travis-ci

- angular/src/app/landing/data-files/data-files.component.spec.ts
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/app/shared/download-service/download-service.service.ts
http://mml.nist.gov:8080/browse/ODD-997
This change is to hide .sha files from the file list on the PDR landing page.
To test, run local docker and make sure no .sha file shows up in the file list.
Sample odid to test:
http://localhost:4200/od/id/66492819760D3FF6E05324570681BA721894
http://localhost:4200/od/id/3CF6F926D7309656E0531A5706810E0D1498
> Hide sha files

- angular/src/app/landing/metadata/metadata.component.html
- angular/src/app/landing/metadata/metadata.component.scss
- angular/src/app/landing/metadata/metadata.component.ts
http://mml.nist.gov:8080/browse/ODD-1001
This check in made the following changes to the JSON viewer:
1. Use light color for the title bar
2. Use blue color for the export button
3. Remove the background color of the expand level buttons ("1", "2", "3" and "View Full Tree") and hover background color to blue
4. Change text color in the title bar to black to meet 508 Compliance
5. Change text color inside the viewer to black to meet 508 Compliance.
> Changed the color of the JSON viewer

- angular/src/app/landing/sections/resourcedata.component.html
http://mml.nist.gov:8080/browse/ODD-1002
This change removes the hover action when user move the mouse over the "Download Data" button or the external link titles.
> Remove hover function for restrict access page

- angular/src/environments/environment.prod.ts
http://mml.nist.gov:8080/browse/ODD-1010
The error was caused by calling remote Web metadata service from client side.
This can be fixed by turning useMetadataService off in environment.prod.ts.
To test, run it in local docker.
> Disable useMetadataService for client side

- angular/src/app/datacart/bundleplan/bundleplan.component.ts
- angular/src/app/shared/download-service/download-service.service.ts
http://mml.nist.gov:8080/browse/ODD-1019
Please refer to the Jira ticket for problem details.
To test, either run the app locally or in docker. If run it locally, set the following in environment.ts
useMetadataService: true,
useCustomizationService: true
editEnabled: false, 
Once bundle downloading starts, and you see download status show up in the file list, click on "x" (cancel) button in "Overall progress" row. Make sure those "downloading" status change to "Canceled". Bundle list should disappear.
> Update download status when user cancels all

- docker/pdrtest/Dockerfile
- docker/pdrtest/verify-asc.sh
- python/nistoar/pdr/preserv/bagger/midas3.py
- python/nistoar/pdr/preserv/bagger/prepupd.py
- python/nistoar/pdr/preserv/bagit/multibag.py
- python/nistoar/pdr/preserv/service/service.py
- python/nistoar/pdr/preserv/service/siphandler.py
- python/nistoar/pdr/publish/midas3/service.py
- python/tests/nistoar/pdr/preserv/bagger/test_midas3.py
- python/tests/nistoar/pdr/preserv/service/test_service_midas3.py
- python/tests/nistoar/pdr/preserv/service/test_siphandler_datacite.py
- python/tests/nistoar/pdr/preserv/service/test_siphandler_midas3.py
- python/tests/nistoar/pdr/preserv/service/test_siphandler_midas3_rm2.py
- python/tests/nistoar/pdr/preserv/service/test_siphandler_restricted.py
- python/tests/nistoar/pdr/publish/midas3/test_service_preserve.py
- python/tests/nistoar/pdr/publish/midas3/test_wsgi_preserve.py
This PR addresses ODD-992 that updates the publishing system to support special processing of SIPs featuring restricted public access. SIPs from MIDAS are recognized as providing data under restricted public access when the POD includes files and an accessURL that points to the new Salesforce-connected Restricted Access Gateway; upon recognition, several bits of metadata are automatically attached to the record that are ultimately used by the Salesforce gateway.  It also applies two bits of specialized handling upon preservation and ingest:  the preservation bag files are sent to a special storage directory to be stored separately from the public data, and the file components are removed from the NERDm record sent to the ingest service.
> Support restricted public access in publishing workflow

- angular/src/app/landing/aboutdataset/aboutdataset.component.scss
- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/data-files/data-files.component.spec.ts
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/styles.scss
http://mml.nist.gov:8080/browse/ODD-1020
This check in replaced the file detail popup with the following:
1. When user mouse over a file name in the tree table, the row will expand and all file details will display there.
2. When mouse leave or user clicks on the file name, the file detail row will be closed if it's open.
3. An arrow next to the file name indicates the status of the file detail row.
4. A "copy to clipboard" button allows user to copy the hash value
5. A screenshot of the file detail row is attached here.
6. To test, run the app locally or in docker. Test case: http://localhost:4200/od/id/mds2-2437
.
> Replaced the file detail popup with row expand

- angular/src/app/landing/metricsinfo/metricsinfo.component.html
http://mml.nist.gov:8080/browse/ODD-1023
This check in fixes the "more" button in the metrics info box in the landing page. It supposed to open the metrics page but is currently link to the about page instead.
A chart icon was also added at front of "More" to make it consistent with the link under "About This Dataset".
To test, run it locally with useMetadataService: true and editEnabled: false in environment.ts. Or run it in docker.
> Fixed 'More' button in Metrics Info box.

- angular/src/app/landing/aboutdataset/aboutdataset.component.html
- angular/src/app/landing/aboutdataset/aboutdataset.component.spec.ts
- angular/src/app/landing/aboutdataset/aboutdataset.component.ts
- angular/src/app/landing/sections/resourceidentity.component.html
- angular/src/app/landing/sections/resourceidentity.component.spec.ts
- angular/src/app/landing/sections/resourceidentity.component.ts
- angular/src/app/nerdm/nerdm.ts
This PR adjusts the display of the isPartOf NERDm property:
*  make collection name a clickable link to the collection page
*  support Aggregation collections, too
*  in "About" section, list all enclosing collections if record is a member of more than one.
*  tweak top reference: italicize and use slightly smaller font.  
Please confirm that unit tests pass and display looks okay.
> Adjust display of isPartOf property

- angular/src/app/landing/sections/resourceidentity.component.css
- angular/src/app/landing/sections/resourceidentity.component.html
- angular/src/app/landing/sections/resourceidentity.component.spec.ts
- angular/src/app/landing/sections/resourcerefs.component.css
- angular/src/app/landing/sections/resourcerefs.component.html
- angular/src/app/landing/sections/resourcerefs.component.spec.ts
- angular/src/app/landing/sections/resourcerefs.component.ts
The main motivation behind this PR is to properly display references that do not include a link to the thing being reference--e.g. a paper that is still "in press".  Previously, if a NERDm reference did not include a `location` property (which provides the URL to the cited thing), the landing was still rendering it as a link, which by default went to the PDR home URL.  With this PR, it is now rendered as regular text.  Supporting this feature required an update to the NERDm core schema (see [oar-metadata PR#50](https://github.com/usnistgov/oar-metadata/pull/50)).
I took this opportunity to fix a few other reference rendering issues:
*  When listing multiple references, the commas  were being prepended with a space; sometimes this would cause the comma to appear on a line by itself.
* …
> Support linkless ("in press") references and fix layout problems

- angular/src/app/landing/resultlist/resultlist.component.ts
- angular/src/app/landing/sections/resourcedata.component.html
- angular/src/app/landing/sections/resourcedata.component.ts
- angular/src/app/nerdm/nerdm.spec.ts
- angular/src/app/nerdm/nerdm.ts
- angular/src/environments/environment.ts
The NERDm schemas allow any type of resource record to include one or more `DynamicResourceSet` components.  Consequently, the dynamic search results should always be displayed--regardless of whether it is a `ScienceTheme` resource or not.  When the resource is a `ScienceTheme` resource, however, the display may be a little different.  Previously, the Landing Page Service code would only display dynamic search results for `ScienceTheme` records.  This PR fixes this.  
This PR also includes some changes to the `NERDResource` class.  Previously (on my advice), we moved a `selectAccessPages()` function from the `ResourceDataComponent` class to the `NERDResource` class; however, on closer inspection, that function included some manipulations specific to the `ResourceDataComponent`.  (More …
> LPS: always display DynamicResourceSets

- angular/src/app/landing/landingpage.component.ts
The Landing Page Service fails to enter editing mode due to an exception in the `LandingPageComponent`'s `setMenuPosition()` function.  It was apparently getting called before the DOM was fully set for the child elements it needed access to; as a result, the function threw an exception when attempting to access a property of the undefined element.  This PR seems to fix the problem and do the right thing: adjusting the menu position as the page transitions between mobile and desktop modes.
> LPS: fix setMenuPosition() exception preventing editing

- angular/src/app/landing/filters/filters.component.ts
- angular/src/app/landing/resultlist/resultlist.component.ts
- angular/src/app/landing/topic/topic.component.ts
This check in fixed following issues:
1. When user selected more than one keyword in the keyword filter, nothing showed up in the search result. 
2. After above fixed, when user selected two keywords in the keyword filter then removed one of them, the search result will be empty.
#1 was because that the search string was not parsed. In SDP, it was parsed in the server side but here we need to parse it in the memory.
#2 was because the suggested keyword lookup table only contained the suggested keywords of latest selected keyword. Once it was removed, the app was unable to locate the original keywords for search.
To test, run the app locally and browse http://localhost:4200/od/id/mds9911.
> Fixed keyword filter issue.

- angular/src/app/landing/topic/topic.component.ts
http://mml.nist.gov:8080/browse/ODD-1051
This checkin fixes the problem that the landing page fails to load if the nerdm record does not have a "theme" field.
To test it locally, run the app with useMetadataService: true and useCustomizationService: true in environment.ts then browse the following url:
http://localhost:4200/od/id/75C6467F8B205670E05324570681995A1967
Or test it in local docker.
> Fixed app error when there is no theme field in nerdm record

- angular/src/app/landing/filters/filters.component.ts
- angular/src/app/landing/resultlist/resultlist.component.ts
Problem: when select "Record has" item in Science Theme collection, we got this error:
Root cause: There is one record with no "components" field.
Solution: Fixed logic to skip the record that has no "components" field.
Test: Run it locally and browse http://localhost:4200/od/id/mds9911. Click on any of the three items under "Record has" in the filters section. Make sure the right side result list display the same number of files as indicated in the filter side.
> Handle record that has no component - caused filter to fail

- angular/src/app/landing/filters/filters.component.ts
This check in fixed some duplicates in the keyword filter dropdown list. For example in the attached screenshot - forensics and forensics(1) are actually the same.
> Fixed duplicates in keyword filter lookup table

- angular/src/app/landing/aboutdataset/aboutdataset.component.spec.ts
- angular/src/app/landing/aboutdataset/aboutdataset.component.ts
- angular/src/app/landing/sections/resourceidentity.component.html
- angular/src/app/landing/sections/resourceidentity.component.spec.ts
- angular/src/app/landing/sections/resourceidentity.component.ts
- angular/src/app/nerdm/nerdm.spec.ts
- angular/src/app/nerdm/nerdm.ts
http://mml.nist.gov:8080/browse/ODD-1059
Detail changes:
For Science Theme landing page
At top of page,  Resource type label => Science Theme Collection
On each Dataset page, change text for
Part of the .... "[science theme name] Collection" both at the top and then About this Collection section
example:  Part of the [Forensic Science Data](https://oardev.nist.gov/od/id/md) Collection
To test: run it locally and use http://localhost:4200/od/id/mds9911. Make sure it displays "Science Theme Collection" on top of the screen:
Then click on any of the data files. In the new tab, change "data.nist.gov" to "localhost:4200". Make sure you see "Part of the Forensics Science Data Collection" at both top of the screen and the "About this Dataset" section at the bottom:
> Modified science theme label

- angular/src/app/landing/searchresult/searchresult.component.html
- angular/src/app/landing/searchresult/searchresult.component.spec.ts
This PR places a heading title for a science theme dataset listing, analogous to the "Files" heading above the file listing on a regular landing page.
> LPS: add title heading to dataset listing

- angular/src/app/landing/landingpage.component.ts
- angular/src/app/landing/resultlist/resultlist.component.ts
- angular/src/app/landing/searchresult/searchresult.component.html
- angular/src/app/landing/searchresult/searchresult.component.ts
- angular/src/app/shared/metrics-service/metrics.service.ts
- angular/src/app/shared/searchfields-list/searchfields-list.service.ts
Fixed the following two issues:
1. The link to metrics page broken: fix: treat /pdr/metrics/mds2-XXXX and /pdr/metrics/ark:/88434/mds2-XXXX the same.
2. Need to collapse the filter panel when science theme page first open.
mds2-2157 can be used to test metrics fix.
> Fixed metrics url; Collapse filter when science theme landing page open

- angular/src/app/landing/topic/topic.component.ts
This PR addresses ODD-1069 ("LPS: Topic component throws exception when scheme is missing") in which the implementation of `TopicComponent`'s `updateResearchTopics()` assumed the record has both `topic` and `theme` properties and that a `topic` always had a `scheme`.  This fixes the issue by adding guards that test for their existence.
> LPS: TopicComponent: guard against missing topic/theme properties

- angular/src/app/landing/author/author.component.html
- angular/src/app/landing/contact/contact.component.html
- angular/src/app/landing/contact/contact.component.ts
- angular/src/app/landing/facilitators/facilitators.component.css
- angular/src/app/landing/facilitators/facilitators.component.html
- angular/src/app/landing/facilitators/facilitators.component.ts
- angular/src/app/landing/resultlist/resultlist.component.html
- angular/src/app/landing/resultlist/resultlist.component.ts
- angular/src/app/landing/sections/resourcedata.component.css
- angular/src/app/landing/sections/resourcedata.component.html
- angular/src/app/landing/sections/resourcedata.component.ts
- angular/src/app/landing/sections/resourceidentity.component.html
- angular/src/app/landing/version/version.component.html
- angular/src/app/landing/version/version.component.ts
http://mml.nist.gov:8080/browse/ODD-1066
This check in has following changes:
1. Set all expansion symbols to the same triangle symbols.
2. Unified the behavior of expansion animation.
3. Added tooltips and alter text to the expansion symbols.
4. Changed the condition  recordType=='Science Theme Collection' to theme == scienceTheme so it won't rely on theme label (otherwise any change to the label will cost app to fail).
> Made expansion symbols consistant; Added tooltip and alter text

- angular/src/app/landing/filters/filters.component.ts
- angular/src/app/landing/resultlist/resultlist.component.ts
http://mml.nist.gov:8080/browse/ODD-1068
This checkin made following 2 changes:
1. In filters section on forensics landing page
1) Expand forensics research topics
2) Collapse completely NIST research topics
2. Fixed the issue that in "Type of resource" and "Record has" sections, selecting more than one item gets no result.
To test it locally, 
1. Set useMetadataService: true, useCustomizationService: true, editEnabled: false in environment.ts.
2. Change "data.nist.gov" to "oardev.nist.gov" in environment.ts.
3. browse http://localhost:4200/lps/pdr0-0001.
> 1.NIST topic list closes on start up. 2.Fixed filter logic.

- angular/src/app/landing/landingpage.component.html
- angular/src/app/landing/landingpage.component.ts
- angular/src/app/landing/resultlist/resultlist.component.html
http://mml.nist.gov:8080/browse/ODD-1071
This fix aligns 'Sort by' dropdown box with page and search boxes. The result should look like attached screenshots in both Chrome and Firefox.
> Align 'Sort by' dropdown box with page and search boxes

- angular/src/app/landing/landingpage.component.ts
- angular/src/app/metrics/metrics.component.ts
- angular/src/app/shared/metrics-service/metrics.service.ts
- angular/src/app/shared/search-service/search-service.service.ts
http://mml.nist.gov:8080/browse/ODD-1064
This fix calculates the total download size from total number of dataset downloads and total number of file downloads. Then display the calculated number instead of the number from metadata.
To test locally, set useMetadataService: true, useCustomizationService: true, and editEnabled: false in environment.ts.
> Display calculated total download size

- angular/src/app/landing/resultlist/resultlist.component.spec.ts
- angular/src/app/landing/resultlist/resultlist.component.ts
http://mml.nist.gov:8080/browse/ODD-1076
Issue: in following page when user clicks on the "Home Page" button of "NIST Short Tandem Repeat DNA Internet DataBase", the "Oops!" error page will display:
https://testdata.nist.gov/od/id/pdr0-0001
Root cause: if landingPage field of a search result item is blank, and user click on "Visit Home Page", the Google Analytics service function will be called and failed because GA service was not defined in this component.
Solution: Add GA service to this component.
> Add Google Analytics service to search result link

- docker/pdrtest/Dockerfile
- python/nistoar/pdr/preserv/service/siphandler.py
- python/tests/nistoar/pdr/preserv/service/test_siphandler_midas3.py
This PR leverages the [updates to oar-metadata (PR#53)](https://github.com/usnistgov/oar-metadata/pull/53) to provide more information in the preservation log when there is a failure while registering/updating a DOI.
> Improve reporting of error messages during DOI updates

- angular/src/app/landing/landingpage.component.spec.ts
- angular/src/app/landing/landingpage.component.ts
This fixes a bug discovered by @pjl1000:  the landing page will fail to render if the NERDm record does not include a components property.  (Note that this is not a required property.)  The fix requires the addition of a guard into  the `useMetadata()` function in `LandingPageComponent` that ensures the property's existence before attempting to calculate the total size of all files combined.
> Fix LPS rendering failure when no components in metadata

- python/nistoar/pdr/preserv/bagger/midas3.py
- python/nistoar/pdr/publish/midas3/service.py
- python/tests/nistoar/pdr/preserv/bagger/test_midas3.py
- python/tests/nistoar/pdr/publish/midas3/test_service_update.py
Currently, when someone updates a previously published record in MIDAS with new or updated files, the changes are sent to review under a new temporary record number--the so-called ghost record.  Meanwhile, the PDR can provide the draft landing page under that new number provided the submitted POD record contains a proper "replaces" property.  That landing page must link simultaneously to the new files and the previously published files that are not being updated.  Currently, there is a bug in the linking to the new files; the landing page service will only look for the files in directories associated with the new number when they actually are still stored under the new one.  This PR fixes this problem by adding the old record data directories to the list that the PDR checks for …
> Bug fix: properly link to data via ghost record

- angular/src/app/datacart/treetable/treetable.component.html
- angular/src/app/frame/footbar.component.html
- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/resultlist/resultlist.component.html
- angular/src/app/landing/sections/resourcedata.component.html
- angular/src/app/landing/sections/resourceidentity.component.html
This PR is in response to a security scan of  the datacart page serving RPA requests.  The scan recommends adding `rel="noopener noreferrer"` to any `<a href="...">` that also has `target="_blank"`.  This would apply to any link generated in the PDR angular application.  
There are two disadvantages to making this recommended change:
*  when the link points to a downloadable file, an access page, or a home page, the use of `noreferrer` prevents target sites from learning that the PDR is driving users to that site, including when that site is the PDR itself.  Note that in most cases, when this type of link does not point to a PDR URL, it points to another `nist.gov` server; thus, "noreferrer" mainly hurts ourselves. 
*  when the link points to a PDR angular URL, use of `noopener` prevents …
> LPS: set rel="noopener" to links with target="_blank"

- angular/src/app/app.component.ts
- angular/src/app/shared/ga-service/google-analytics.service.ts
Google Analytics is not notified when we route to a page inside SPA. To fix that, we subscribe to the Angular router inside the app.component.ts file and send the new routes to Google Analytics.
PDR does not route to a page inside the app so it does not has this issue so far. But I added this piece of code here as a standard GA4 implementation.
> Handle page view for SPA

- angular/src/app/landing/landingpage.component.ts
- angular/src/app/metrics/metrics.component.spec.ts
- angular/src/app/metrics/metrics.component.ts
Removed the code that read file level metrics which wasn't used in landing page.
> Do not read file level metrics data for landing page

- angular/src/app/app.component.ts
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/app/landing/landingpage.component.ts
- angular/src/app/metrics/horizontal-barchart/horizontal-barchart.component.ts
- angular/src/app/metrics/metrics.component.html
- angular/src/app/metrics/metrics.component.ts
- angular/src/app/shared/metrics-service/metrics.service.ts
Issue: landing page crashed when metrics data didn't have filepath info.
Example: https://testdata.nist.gov/od/id/66AF4AFEA96764C4E0532457068100261895
Fix: Check filepath attribute before using it.
Testing: To test using testdata.nist.gov as backend, in environment.ts set useMetadataService: true, useCustomizationService: true and replace data.nist.gov with testdata.nist.gov. 
Test samples:
http://localhost:4200/metrics/mds2-2124
http://localhost:4200/lps/mds2-2124
http://localhost:4200/metrics/576CE869311197F3E0531A570681C5C71857
http://localhost:4200/lps/576CE869311197F3E0531A570681C5C71857
> Handle metrics that has no filepath

- angular/src/app/landing/data-files/data-files.component.html
- angular/src/app/landing/data-files/data-files.component.ts
This check in fixed following issue:
Issue: In the file list, download button showed up for folders which should not.
The column title that sometime display "Status" and sometime "Access" was by design. The default name is "Status". But when access level is 'restricted public', it changes to "Access". Here is the code:
if(this.record['accessLevel'] === 'restricted public') {
this.checkAccessPageType();
this.cols[3]['header'] = "Access";
}
To test the app locally, set the following config in environment.ts:
useMetadataService: true,
useCustomizationService: true
And change data.nist.gov to testdata.nist.gov if necessary.
Test case: 
http://localhost:4200/lps/mds2-2909 (in testdata.nist.gov)
http://localhost:4200/lps/mds2-2645 (in data.nist.gov)
> Hide download button for folders

- angular/src/app/datacart/cart.service.ts
- angular/src/app/datacart/datacart.component.css
- angular/src/app/datacart/datacart.component.html
- angular/src/app/datacart/datacart.component.ts
This PR improves error handling and UI feedback for dataset availability within the datacart. 
- Added a property to track success or failure: in the data cart component **isCartLoadedSuccessfully** is used to track if the cart was loaded successfully. **isCartLoadedSuccessfully** is set to true if the result is successfully received and it's not null or empty. If there's an error or the result is null, we set it to false.
- Added ***ngIf** directive to the **app-treetable** element: in the datacart component's HTML template, we use the ***ngIf** directive to conditionally render the **app-treetable** element based on the **isCartLoadedSuccessfully** property.
- Updated the error handling logic in the **getRpaCart()** of the datacart service:  when an error occurs, we check the error …
> Improve Error Handling and UI Feedback for Dataset Availability

- angular/src/app/landing/keyword/keyword.component.html
- angular/src/app/landing/topic/topic.component.html
Fixed topic and keyword wrapping issue in Firefox and Safari.
Tested locally.
> Fixed wrapping issue in forefox and Safari

- angular/src/app/landing/filters/filters.component.ts
- angular/src/app/landing/resultlist/resultlist.component.ts
- angular/src/app/shared/search-service/search-service.service.ts
The issue with the search box has been fixed.
Also the "Clear all" button will truly clear everything this time.
May want to deploy to oardev first to let more people play with it before go to production.
> Fixed search filter issue in result list panel

- angular/src/app/datacart/bundleplan/bundleplan.component.ts
- angular/src/app/shared/download-service/download-service.service.ts
This PR updates the logic for generating bundle names in the datacart to address Greg's feedback.
New name format: **NIST-Data-[timestamp]**, where timestamp is in a human readable format: `YYYY-MM-DDTHH-MM`.
1. Updated `generateZipFileName` Method
- The new implementation generates a file name based on the current timestamp:
```typescript
private generateZipFileName(base: string = "NIST-Data"): string {
const now = new Date();
const timestamp = now.toISOString().slice(0, 16).replace(":", "-");
return `${base}-${timestamp}`;
}
```
2. Replaced Bundle Name Logic
- Updated references to use the new method:
```typescript
let bundleBaseName = this.generateZipFileName("NIST-Data");
```
- These changes were tested locally using `oar-docker` to verify that the bundle names align with the new …
> Rename Bundle Name

- angular/src/app/_helpers/fakeBackendInterceptor.ts
- angular/src/app/landing/contact/contact.component.html
- angular/src/app/landing/facilitators/facilitators.component.html
- angular/src/app/landing/filters/filters.component.html
- angular/src/app/landing/filters/filters.component.ts
- angular/src/app/landing/landingpage.component.html
- angular/src/app/landing/landingpage.component.scss
- angular/src/app/landing/landingpage.component.ts
- angular/src/app/landing/resultlist/resultlist.component.html
- angular/src/app/landing/resultlist/resultlist.component.ts
- angular/src/app/landing/searchresult/searchresult.component.html
- angular/src/app/landing/searchresult/searchresult.component.ts
- angular/src/app/landing/taxonomy/taxonomy.component.html
- angular/src/app/landing/taxonomy/taxonomy.component.ts
- angular/src/app/shared/collection-service/collection.service.ts
This branch fixes two issues:
1. When expand/collapse filter items, white space added to the top area of landing page. This issue only happened in Firefox.
2. Search result return nothing if taxonomy tag contains comma.
Issue #1 was because of a Firefox bug related to sticky styling. The fix was to use absolute position and dynamic position.
Issue #2 was fixed by replacing filter string with object.
Tested locally in Chrome, Firefox and Safari. Not tested in docker because had some issues running docker locally even integration branch - rmm had problem accessing Mongodb.
> Fixed Firefox issues

- angular/src/app/datacart/cart.service.ts
This PR is part of an effort to make zip files created via the data cart more human-oriented; this one addresses the name assigned to zip files containing RPA data.
> Set data cart zip file names to be more human-oriented

- .github/workflows/angular-source.yml
- .github/workflows/java-source.yml
- angular/src/app/bulk-download/bulk-download.component.html
- angular/src/app/bulk-download/bulk-download.component.spec.ts
- angular/src/app/bulk-download/bulk-download.component.ts
- angular/src/app/landing/data-files/data-files.component.ts
- angular/src/app/landing/tools/menu.component.ts
For various reasons, the nginx URL mapping is not able to properly map the links to the bulkdownload page; thus, the links would not work under oar-docker.  To address this in this PR, absolute URLs are formed using base URLs pulled from the configuration.  (Similarly, the URL for downloading the script is now formed in a similar way.)
Also fixed is the rendering of the script execution examples on the bulkdownload page which were not showing up when accessed via the `/bulkdownloads` route (i.e. without an id included).  
Finally, two GitHub Action config files were updated to upgrade from a deprecating version of the cache action.
> Fix URLs linking to bulkdownload page to work under oar-docker
